id: b3133dd6d3ea4dd89de63becb29154fc
initial_creation_type: ocr
source_metadata:
  volumes:
    9dee60c4765e4db4b375099aae81bcd9:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
